export const currencyOptionEn = [
    { value: 'AED', label: 'AED - United Arab Emirates Dirham' },
    { value: 'ARS', label: 'ARS - Argentine Peso' },
    { value: 'AUD', label: 'AUD - Australian Dollar' },
    { value: 'BDT', label: 'BDT - Bangladeshi Taka' },
    { value: 'BHD', label: 'BHD - Bahraini Dinar' },
    { value: 'BRL', label: 'BRL - Brazilian Real' },
    { value: 'CAD', label: 'CAD - Canadian Dollar' },
    { value: 'CHF', label: 'CHF - Swiss Franc' },
    { value: 'CLP', label: 'CLP - Chilean Peso' },
    { value: 'CNY', label: 'CNY - Chinese Yuan' },
    { value: 'COP', label: 'COP - Colombian Peso' },
    { value: 'CZK', label: 'CZK - Czech Koruna' },
    { value: 'DKK', label: 'DKK - Danish Krone' },
    { value: 'DZD', label: 'DZD - Algerian Dinar' },
    { value: 'EGP', label: 'EGP - Egyptian Pound' },
    { value: 'EUR', label: 'EUR - Euro' },
    { value: 'GBP', label: 'GBP - British Pound' },
    { value: 'HKD', label: 'HKD - Hong Kong Dollar' },
    { value: 'IDR', label: 'IDR - Indonesian Rupiah' },
    { value: 'ILS', label: 'ILS - Israeli Shekel' },
    { value: 'INR', label: 'INR - Indian Rupee' },
    { value: 'JPY', label: 'JPY - Japanese Yen' },
    { value: 'JOD', label: 'JOD - Jordanian Dinar' },
    { value: 'KRW', label: 'KRW - South Korean Won' },
    { value: 'KWD', label: 'KWD - Kuwaiti Dinar' },
    { value: 'KZT', label: 'KZT - Kazakhstani Tenge' },
    { value: 'LBP', label: 'LBP - Lebanese Pound' },
    { value: 'LKR', label: 'LKR - Sri Lankan Rupee' },
    { value: 'MAD', label: 'MAD - Moroccan Dirham' },
    { value: 'MGA', label: 'MGA - Malagasy Ariary' },
    { value: 'MXN', label: 'MXN - Mexican Peso' },
    { value: 'MYR', label: 'MYR - Malaysian Ringgit' },
    { value: 'NGN', label: 'NGN - Nigerian Naira' },
    { value: 'NOK', label: 'NOK - Norwegian Krone' },
    { value: 'NZD', label: 'NZD - New Zealand Dollar' },
    { value: 'OMR', label: 'OMR - Omani Rial' },
    { value: 'PHP', label: 'PHP - Philippine Peso' },
    { value: 'PKR', label: 'PKR - Pakistani Rupee' },
    { value: 'PLN', label: 'PLN - Polish Złoty' },
    { value: 'QAR', label: 'QAR - Qatari Riyal' },
    { value: 'RUB', label: 'RUB - Russian Ruble' },
    { value: 'SAR', label: 'SAR - Saudi Riyal' },
    { value: 'SEK', label: 'SEK - Swedish Krona' },
    { value: 'SGD', label: 'SGD - Singapore Dollar' },
    { value: 'THB', label: 'THB - Thai Baht' },
    { value: 'TND', label: 'TND - Tunisian Dinar' },
    { value: 'TRY', label: 'TRY - Turkish Lira' },
    { value: 'UAH', label: 'UAH - Ukrainian Hryvnia' },
    { value: 'USD', label: 'USD - United States Dollar' },
    { value: 'VND', label: 'VND - Vietnamese Đồng' },
    { value: 'XAF', label: 'XAF - Central African CFA Franc' },
    { value: 'XOF', label: 'XOF - West African CFA Franc' },
    { value: 'ZAR', label: 'ZAR - South African Rand' }
];

export const currencyOptionsFr = [
    { value: 'AED', label: 'AED - Dirham des Émirats arabes unis' },
    { value: 'ARS', label: 'ARS - Peso argentin' },
    { value: 'AUD', label: 'AUD - Dollar australien' },
    { value: 'BDT', label: 'BDT - Taka bangladais' },
    { value: 'BHD', label: 'BHD - Dinar bahreïni' },
    { value: 'BRL', label: 'BRL - Réal brésilien' },
    { value: 'CAD', label: 'CAD - Dollar canadien' },
    { value: 'CHF', label: 'CHF - Franc suisse' },
    { value: 'CLP', label: 'CLP - Peso chilien' },
    { value: 'CNY', label: 'CNY - Yuan chinois' },
    { value: 'COP', label: 'COP - Peso colombien' },
    { value: 'CZK', label: 'CZK - Couronne tchèque' },
    { value: 'DKK', label: 'DKK - Couronne danoise' },
    { value: 'DZD', label: 'DZD - Dinar algérien' },
    { value: 'EGP', label: 'EGP - Livre égyptienne' },
    { value: 'EUR', label: 'EUR - Euro' },
    { value: 'GBP', label: 'GBP - Livre sterling' },
    { value: 'HKD', label: 'HKD - Dollar de Hong Kong' },
    { value: 'IDR', label: 'IDR - Roupie indonésienne' },
    { value: 'ILS', label: 'ILS - Shekel israélien' },
    { value: 'INR', label: 'INR - Roupie indienne' },
    { value: 'JPY', label: 'JPY - Yen japonais' },
    { value: 'JOD', label: 'JOD - Dinar jordanien' },
    { value: 'KRW', label: 'KRW - Won sud-coréen' },
    { value: 'KWD', label: 'KWD - Dinar koweïtien' },
    { value: 'KZT', label: 'KZT - Tenge kazakh' },
    { value: 'LBP', label: 'LBP - Livre libanaise' },
    { value: 'LKR', label: 'LKR - Roupie srilankaise' },
    { value: 'MAD', label: 'MAD - Dirham marocain' },
    { value: 'MGA', label: 'MGA - Ariary malgache' },
    { value: 'MXN', label: 'MXN - Peso mexicain' },
    { value: 'MYR', label: 'MYR - Ringgit malaisien' },
    { value: 'NGN', label: 'NGN - Naira nigérian' },
    { value: 'NOK', label: 'NOK - Couronne norvégienne' },
    { value: 'NZD', label: 'NZD - Dollar néo-zélandais' },
    { value: 'OMR', label: 'OMR - Rial omanais' },
    { value: 'PHP', label: 'PHP - Peso philippin' },
    { value: 'PKR', label: 'PKR - Roupie pakistanaise' },
    { value: 'PLN', label: 'PLN - Złoty polonais' },
    { value: 'QAR', label: 'QAR - Riyal qatari' },
    { value: 'RUB', label: 'RUB - Rouble russe' },
    { value: 'SAR', label: 'SAR - Riyal saoudien' },
    { value: 'SEK', label: 'SEK - Couronne suédoise' },
    { value: 'SGD', label: 'SGD - Dollar de Singapour' },
    { value: 'THB', label: 'THB - Baht thaïlandais' },
    { value: 'TND', label: 'TND - Dinar tunisien' },
    { value: 'TRY', label: 'TRY - Livre turque' },
    { value: 'UAH', label: 'UAH - Hryvnia ukrainienne' },
    { value: 'USD', label: 'USD - Dollar des États-Unis' },
    { value: 'VND', label: 'VND - Đồng vietnamien' },
    { value: 'XAF', label: 'XAF - Franc CFA d\'Afrique centrale' },
    { value: 'XOF', label: 'XOF - Franc CFA d\'Afrique de l\'Ouest' },
    { value: 'ZAR', label: 'ZAR - Rand sud-africain' }
];

