export const RouteList = {
    'HOME': '/',
    'WELCOME': '/welcome-page',
    'LOGIN': '/login',
    'DASHBOARD': '/dashboard',
    'INVENTORY_PURCHASE': '/inventory/purchase',
    'INVENTORY_SALES': '/inventory/sales',
    'INVENTORY_SALES_NEW': '/inventory/sales/new',
    'INVENTORY_PURCHASE_NEW': '/inventory/purchase/new',
    'STOCK_SITUATION': '/inventory/stock_situation',
    'INVOICE': '/inventory/invoices',
    'GENERALE': '/settings/general',
    'PROFILE': '/settings/profile',
    'USER': '/settings/user',
    'CATEGORY': '/settings/category',
    'UNIT': '/settings/unit',
    'PRODUCT': '/settings/product',
    'EXPENSE_TYPE': '/settings/expenses_type',
    'EXPENSES': '/expenses',
    'CASH_SUMMARY': '/cash_summary',
};